/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelegramWarehouseRouteImport } from './routes/api/public/telegram/warehouse'
import { Route as ApiPublicTelegramShopRouteImport } from './routes/api/public/telegram/shop'
import { Route as ApiPublicTelegramSetupRouteImport } from './routes/api/public/telegram/setup'
import { Route as ApiPublicTelegramHealthRouteImport } from './routes/api/public/telegram/health'
import { Route as ApiPublicTelegramAdminRouteImport } from './routes/api/public/telegram/admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWarehouseRoute =
  ApiPublicTelegramWarehouseRouteImport.update({
    id: '/api/public/telegram/warehouse',
    path: '/api/public/telegram/warehouse',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramShopRoute = ApiPublicTelegramShopRouteImport.update({
  id: '/api/public/telegram/shop',
  path: '/api/public/telegram/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramSetupRoute = ApiPublicTelegramSetupRouteImport.update({
  id: '/api/public/telegram/setup',
  path: '/api/public/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramHealthRoute = ApiPublicTelegramHealthRouteImport.update({
  id: '/api/public/telegram/health',
  path: '/api/public/telegram/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramAdminRoute = ApiPublicTelegramAdminRouteImport.update({
  id: '/api/public/telegram/admin',
  path: '/api/public/telegram/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/telegram/admin': typeof ApiPublicTelegramAdminRoute
  '/api/public/telegram/health': typeof ApiPublicTelegramHealthRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/shop': typeof ApiPublicTelegramShopRoute
  '/api/public/telegram/warehouse': typeof ApiPublicTelegramWarehouseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/telegram/admin': typeof ApiPublicTelegramAdminRoute
  '/api/public/telegram/health': typeof ApiPublicTelegramHealthRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/shop': typeof ApiPublicTelegramShopRoute
  '/api/public/telegram/warehouse': typeof ApiPublicTelegramWarehouseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/telegram/admin': typeof ApiPublicTelegramAdminRoute
  '/api/public/telegram/health': typeof ApiPublicTelegramHealthRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/shop': typeof ApiPublicTelegramShopRoute
  '/api/public/telegram/warehouse': typeof ApiPublicTelegramWarehouseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/telegram/admin'
    | '/api/public/telegram/health'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/shop'
    | '/api/public/telegram/warehouse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/telegram/admin'
    | '/api/public/telegram/health'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/shop'
    | '/api/public/telegram/warehouse'
  id:
    | '__root__'
    | '/'
    | '/api/public/telegram/admin'
    | '/api/public/telegram/health'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/shop'
    | '/api/public/telegram/warehouse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicTelegramAdminRoute: typeof ApiPublicTelegramAdminRoute
  ApiPublicTelegramHealthRoute: typeof ApiPublicTelegramHealthRoute
  ApiPublicTelegramSetupRoute: typeof ApiPublicTelegramSetupRoute
  ApiPublicTelegramShopRoute: typeof ApiPublicTelegramShopRoute
  ApiPublicTelegramWarehouseRoute: typeof ApiPublicTelegramWarehouseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/warehouse': {
      id: '/api/public/telegram/warehouse'
      path: '/api/public/telegram/warehouse'
      fullPath: '/api/public/telegram/warehouse'
      preLoaderRoute: typeof ApiPublicTelegramWarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/shop': {
      id: '/api/public/telegram/shop'
      path: '/api/public/telegram/shop'
      fullPath: '/api/public/telegram/shop'
      preLoaderRoute: typeof ApiPublicTelegramShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/setup': {
      id: '/api/public/telegram/setup'
      path: '/api/public/telegram/setup'
      fullPath: '/api/public/telegram/setup'
      preLoaderRoute: typeof ApiPublicTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/health': {
      id: '/api/public/telegram/health'
      path: '/api/public/telegram/health'
      fullPath: '/api/public/telegram/health'
      preLoaderRoute: typeof ApiPublicTelegramHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/admin': {
      id: '/api/public/telegram/admin'
      path: '/api/public/telegram/admin'
      fullPath: '/api/public/telegram/admin'
      preLoaderRoute: typeof ApiPublicTelegramAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicTelegramAdminRoute: ApiPublicTelegramAdminRoute,
  ApiPublicTelegramHealthRoute: ApiPublicTelegramHealthRoute,
  ApiPublicTelegramSetupRoute: ApiPublicTelegramSetupRoute,
  ApiPublicTelegramShopRoute: ApiPublicTelegramShopRoute,
  ApiPublicTelegramWarehouseRoute: ApiPublicTelegramWarehouseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
